main: com.github.koxsosen.bukkit.BukkitPluginLoader
name: SimpleVoiceBans-Java8-hardcode_trueproxy
api-version: 1.13
version: 1.0-1.3
softdepend:
  - LibertyBans
depend: [ voicechat ]
author: KoxSosen, Fox Ritch(Foxtanium)
permissions:
  simplevoicebans.actionbar:
    description: Sends an action bar if the player has the permission.
    default: false
